[project]
name = "mcp-notmuch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "html2text>=2024.2.26",
    "mcp[cli]===1.2.0rc1",
    "notmuch>=0.29.2",
]
